### ISSUE TITLE
有什么办法可以在Github上面也正常显示Typora中的格式吗

### ISSUE THREAD

**Issue by cell-juicy** [Cell1344/Note-on-Tao-Zhexuan-real-analysis#1]
比如支持数学公式与颜色标注这些

**Comment by Dragon1573** [comment]
可以考虑使用 [MathJax Plugin for Github](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima) 插件，支持 Google Chrome 和 Microsoft Edge 。安装插件后就可以正常显示了，不过这个插件目前仅支持 GitHub 。

![image](https://user-images.githubusercontent.com/49941141/201064812-ef5ce761-3683-4fed-b76a-6e6e37203518.png)
